Add solutions for 03-lection
js-tasks-ru/htmlcss-20210513_irookanji pull request #3
Opened 2021-05-28 09:51 UTC by irookanji

2021-05-30 12:14 UTC, GSemikozov requested changes

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/01-button/README.md
> +# Кнопка
это системный файл, его не стоит добавлять в ПР

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  margin: 10px;
внешние отступы мы добавляем всегда через родительский блок, а не через сам описываемый блок (так делается для того, чтобы мы могли с легкостью встраивать нашу кнопку куда угодно, и уже там, где мы ее встраиваем, и будем задавать какие-то специфические отступы)

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button:hover:not([disabled]) {
здесь лучше все-таки указать что ховер для .button--primary

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
и еще - чтобы пользователь не мог нажать на кнопку - `pointer-events: none`

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/01-button/test/solution.test.js
> +const expect = require('chai').expect;
это тоже системный файл, его нужно удрать из ПР

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/02-accordion/README.md
> +# Аккордеон
и еще один системный файл)

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary:focus{
с 13 до 19 строки - если это общий сброс стилей (указываем через селекторы тегов), то тогда надо вынести код в общие стили по сбросу. Если же хотим определить в контексте компонента - тогда нужно использовать БЭМ-классы (accordion__item и accordion__summary)

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  height: 72px;
если зафиксируем высоту - то наш аккордион всегда будет не выше 72 пикселей)

2021-05-30 12:14 UTC, GSemikozov commented on 03-lection1/02-accordion/test/solution.test.js
> +const expect = require('chai').expect;
и снова системный фал)

2021-05-30 12:14 UTC, GSemikozov commented on components/footer/footer.css
> +@import '../../assets/fonts/fonts.css';
фонты у нас доступны глобально, поэтому не стоит подключать их в каждый компонент отдельно

2021-05-30 12:14 UTC, GSemikozov commented on components/header/header.css
> +.header__block {
мне кажется, немного бесполезный блок - пусть высота хедера определяется его внутренним содержимым (мы ведь туда добавим и верхнюю панель, и тайтл, и нижний блок с табами, а на внутренней странице компонента - наоборот уберем все кроме верхней панели..)

2021-05-30 12:14 UTC, GSemikozov commented on components/main/main.css
> +.menu {
.menu - надо бы вынести в отдельный блок / компонент

2021-05-30 12:14 UTC, GSemikozov commented on components/main/main.css
> +.component {
компонент и другие блоки тоже стоит унести в отдельный папки / файлы, поскольку они не являются по сути блоком .main

2021-05-30 12:14 UTC, GSemikozov commented on components/preview/preview.css
> +.preview {
у нас уже есть preview-flex,  этот preview можно удалить ;)

2021-06-01 18:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-01 18:46 UTC, irookanji commented on 03-lection1/01-button/README.md
> +# Кнопка
Я его не изменял(не добавлял). Возможно я неправильно спулился с мастера

2021-06-01 18:46 UTC, irookanji commented on 03-lection1/01-button/button.css
> +  margin: 10px;
поправил

2021-06-01 18:46 UTC, irookanji commented on 03-lection1/01-button/button.css
> +.button:hover:not([disabled]) {
поправил

2021-06-01 18:46 UTC, irookanji commented on 03-lection1/01-button/button.css
> +  cursor: default;
поправил

2021-06-01 18:47 UTC, irookanji commented on 03-lection1/01-button/test/solution.test.js
> +const expect = require('chai').expect;
Я его не изменял

2021-06-01 18:47 UTC, irookanji commented on components/footer/footer.css
> +@import '../../assets/fonts/fonts.css';
поправил

2021-06-01 18:47 UTC, irookanji commented on components/header/header.css
> +.header__block {
поправил

2021-06-01 18:47 UTC, irookanji commented on components/main/main.css
> +.menu {
поправил

2021-06-01 18:47 UTC, irookanji commented on components/main/main.css
> +.component {
поправил

2021-06-01 18:47 UTC, irookanji commented on components/preview/preview.css
> +.preview {
поправил

2021-06-01 18:48 UTC, irookanji commented on 03-lection1/02-accordion/README.md
> +# Аккордеон
Я его не изменял

2021-06-01 18:49 UTC, irookanji commented on 03-lection1/02-accordion/test/solution.test.js
> +const expect = require('chai').expect;
я его не изменял)

2021-06-01 19:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-01 19:03 UTC, irookanji commented on 03-lection1/02-accordion/accordion.css
> +summary:focus{
Поправил

2021-06-01 19:03 UTC, irookanji commented on 03-lection1/02-accordion/accordion.css
> +  height: 72px;
Поправил

2021-06-01 19:13 UTC, GSemikozov approved these changes

2021-06-01 19:13 UTC, merged